### PR TITLE
Add TLS Keep Alive to improve performance

### PR DESCRIPTION
**Pull request by jfmyers9**
Signed-off-by: Connor Braa <cbraa@pivotal.io>

### CODE REVIEW

**Comment by sykesm** [comment]
So, silly question: This appears to be adding TCP keep alive; what we need is HTTP Keep-Alive. HTTP 1.1 and better automatically do keep alive the idle connection pool size in our transports so we get limited to a max of 2 idle connections.

Do we know that this is helping?

**Comment by fraenkel** [comment]
Not to pile on, but it seems no one is setting the timeouts appropriately.
The conn state management is also a bit off since its using WaitGroup improperly.  I would suggest someone just lifting was has been done in GoRouter as the starting point.

**Comment by jfmyers9** [comment]
@sykesm Fair. I have less context on this change than @cwlbraa. Adding him to the conversation so that he can contribute.

@fraenkel Sounds like a good suggestion. We should take another pass at the connection state management with that in mind.

**Comment by cwlbraa** [comment]
it had the appearance of making inigo run faster, but we can look at doing http keepalive as well. the timeouts thing– and the implementation of tcp keepalive here– is stolen directly from the http stdlib package: http://golang.org/src/net/http/server.go?s=59426:59517#L2013 , not that that's any excuse.

**Pull request merged**
